import {
  PDFDocument,
  StandardFonts,
  rgb,
} from 'pdf-lib'

type InvoicePdfData = {
  id: string
  customerName: string
  planName: string
  billingCycle: string
  billingPeriodStart: string
  billingPeriodEnd: string
  amount: number
  dueDate: string
  status: string
  createdAt: string
  creditNotes: {
    amount: number
    reason: string
    createdAt: string
  }[]
}

export async function generateInvoicePdf(
  invoice: InvoicePdfData
) {
  const pdfDoc = await PDFDocument.create()

  const page = pdfDoc.addPage([595, 842])

  const regularFont = await pdfDoc.embedFont(
    StandardFonts.Helvetica
  )

  const boldFont = await pdfDoc.embedFont(
    StandardFonts.HelveticaBold
  )

  const { width, height } = page.getSize()

  let y = height - 60

  // Header
  page.drawText('INVOICE', {
    x: 50,
    y,
    size: 28,
    font: boldFont,
    color: rgb(0.1, 0.1, 0.1),
  })

  page.drawText(
    `Invoice ID: ${invoice.id}`,
    {
      x: 50,
      y: y - 30,
      size: 9,
      font: regularFont,
      color: rgb(0.4, 0.4, 0.4),
    }
  )

  page.drawText(
    `Created: ${formatDate(invoice.createdAt)}`,
    {
      x: 50,
      y: y - 45,
      size: 9,
      font: regularFont,
      color: rgb(0.4, 0.4, 0.4),
    }
  )

  // Status
  page.drawText(
    `Status: ${invoice.status}`,
    {
      x: width - 180,
      y,
      size: 11,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    }
  )

  y -= 100

  // Customer
  page.drawText('BILL TO', {
    x: 50,
    y,
    size: 10,
    font: boldFont,
  })

  y -= 20

  page.drawText(invoice.customerName, {
    x: 50,
    y,
    size: 13,
    font: boldFont,
  })

  y -= 50

  // Subscription details
  page.drawText('SUBSCRIPTION', {
    x: 50,
    y,
    size: 10,
    font: boldFont,
  })

  y -= 22

  page.drawText(
    `Plan: ${invoice.planName}`,
    {
      x: 50,
      y,
      size: 10,
      font: regularFont,
    }
  )

  y -= 18

  page.drawText(
    `Billing cycle: ${invoice.billingCycle}`,
    {
      x: 50,
      y,
      size: 10,
      font: regularFont,
    }
  )

  y -= 18

  page.drawText(
    `Billing period: ${invoice.billingPeriodStart} - ${invoice.billingPeriodEnd}`,
    {
      x: 50,
      y,
      size: 10,
      font: regularFont,
    }
  )

  y -= 18

  page.drawText(
    `Due date: ${invoice.dueDate}`,
    {
      x: 50,
      y,
      size: 10,
      font: regularFont,
    }
  )

  y -= 55

  // Amount section
  page.drawRectangle({
    x: 50,
    y: y - 45,
    width: width - 100,
    height: 65,
    borderWidth: 1,
    borderColor: rgb(0.85, 0.85, 0.85),
  })

  page.drawText('Invoice Amount', {
    x: 70,
    y: y - 10,
    size: 10,
    font: regularFont,
    color: rgb(0.4, 0.4, 0.4),
  })

  page.drawText(`INR${invoice.amount.toFixed(2)}`, {
    x: 70,
    y: y - 32,
    size: 18,
    font: boldFont,
  })

  y -= 95

  // Credit notes
  if (invoice.creditNotes.length > 0) {
    page.drawText('CREDIT NOTES', {
      x: 50,
      y,
      size: 10,
      font: boldFont,
    })

    y -= 25

    let totalCredits = 0

    for (const creditNote of invoice.creditNotes) {
      totalCredits += Number(creditNote.amount)

      page.drawText(
        `INR${Number(creditNote.amount).toFixed(2)}`,
        {
          x: 50,
          y,
          size: 10,
          font: boldFont,
        }
      )

      page.drawText(creditNote.reason, {
        x: 140,
        y,
        size: 10,
        font: regularFont,
      })

      page.drawText(
        formatDate(creditNote.createdAt),
        {
          x: width - 140,
          y,
          size: 9,
          font: regularFont,
          color: rgb(0.4, 0.4, 0.4),
        }
      )

      y -= 20
    }

    y -= 10

    page.drawText(
      `Total credited: INR${totalCredits.toFixed(2)}`,
      {
        x: 50,
        y,
        size: 11,
        font: boldFont,
      }
    )

    y -= 25

    const remainingBalance =
      invoice.amount - totalCredits

    page.drawText(
      `Remaining balance: INR${remainingBalance.toFixed(2)}`,
      {
        x: 50,
        y,
        size: 12,
        font: boldFont,
      }
    )
  }

  // Footer
  page.drawText(
    'Generated by Subscription Billing',
    {
      x: 50,
      y: 35,
      size: 8,
      font: regularFont,
      color: rgb(0.5, 0.5, 0.5),
    }
  )

  return await pdfDoc.save()
}

function formatDate(date: string) {
  return new Date(date).toLocaleDateString('en-IN')
}